name: CI/CD pipeline

# Khi xảy ra sự kiện pull request vào nhánh main -> thực hiện
on:
  pull_request:
    branches:
      - develop

jobs:
  # Job 1: Build và test trên máy ảo Ubuntu
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Sử dụng action để checkout code từ repo vào máy ảo
      - name: Checkout code
        uses: actions/checkout@v2

      # Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build và test image được build ra bởi Docker
      - name: Build and test image by Docker
        run: |
          sudo docker build -t chat-app .
          sudo docker run chat-app npm test

      # Push image to Docker Hub
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest

  # Job 2: Deploy lên EC2
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest
          sudo docker stop chat-app || true
          sudo docker rm chat-app || true
          sudo docker run --name chat-app-1 -d -p 3000:3000 baocules/chat-app:latest  \
            -e PORT=${{secrets.PORT}} \
            -e ATLAS_URI=${{secrets.ATLAS_URI}} \
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
